name: Build and Push Docker Image

# Trigger the workflow on pushes to the main branch and on pull requests
on:
  workflow_dispatch:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
permissions:
  packages: write  # Required to push to GitHub Container Registry
  contents: read   # Required to clone the repository

jobs:
  build:
    runs-on: ubuntu-latest
    environment: prod
    permissions:
      contents: 'write'
      id-token: 'write'
      packages: 'read'

    steps:
      - name: Debug
        run: echo "$GITHUB_CONTEXT"

      - name: 'Dynamical variables'
        id: 'vars'
        run: |-
          echo "full_version=v$(npm pkg get version | jq -r)" >> $GITHUB_OUTPUT
          echo "origin=https://${{ github.repository_owner }}:${{ secrets.PERSONAL_ACCESS_TOKEN }}@github.com/${{ github.repository }}" >> $GITHUB_OUTPUT
          
      # Check out the code
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

      - name: Bump Version & Push
        if: github.event_name == 'push'
        run: |
          git config --local user.email "gangs-bot@guludoc.com"
          git config --local user.name "Gangs Bot"
          git remote set-url origin ${{ steps.vars.outputs.origin }}
          npm version patch --force -m "[ci skip] v%s"
          git push 

      - name: 'GIT meta data'
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ghcr.io/${{ github.repository_owner }}/learning-nextauth
          # generate Docker tags based on events and attributes
          tags: |
            type=sha
            type=semver,pattern={{version}},value=${{ steps.vars.outputs.full_version }}
            type=semver,pattern={{major}}.{{minor}},value=${{ steps.vars.outputs.full_version }}
            type=semver,pattern={{major}},value=${{ steps.vars.outputs.full_version }}

      # Set up QEMU
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      # Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with :
          install: true

      # Log in to Docker Hub (or GitHub Container Registry)
#      - name: Log in to Docker Hub
#        if: github.event_name == 'push' || github.event_name == 'workflow_dispatch'
#        uses: docker/login-action@v2
#        with:
#          username: ${{ secrets.DOCKER_USERNAME }}
#          password: ${{ secrets.DOCKER_PASSWORD }}

      # Log in to GitHub Container Registry
      - name: Log in to GitHub Container Registry
        if: github.event_name == 'push' || github.event_name == 'workflow_dispatch'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm64
          push: ${{ github.event_name == 'push' || github.event_name == 'workflow_dispatch' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      # Example: You could add a second tag for GitHub SHA
      # tags: username/nextjs-app:latest,username/nextjs-app:${{ github.sha }}
