name: Build and Push Docker Image

# Trigger the workflow on pushes to the main branch and on pull requests
on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
permissions:
  packages: write  # Required to push to GitHub Container Registry
  contents: read   # Required to clone the repository

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Check out the code
      - name: Checkout code
        uses: actions/checkout@v4

      # Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with :
          install: true

      # Log in to Docker Hub (or GitHub Container Registry)
#      - name: Log in to Docker Hub
#        if: github.event_name == 'push' || github.event_name == 'workflow_dispatch'
#        uses: docker/login-action@v2
#        with:
#          username: ${{ secrets.DOCKER_USERNAME }}
#          password: ${{ secrets.DOCKER_PASSWORD }}

      # Log in to GitHub Container Registry
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker Image
        if: github.event_name == 'pull_request'
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm64
          push: false
          tags: ghcr.io/${{ github.repository_owner  }}/learning-nextauth:latest, ghcr.io/${{ github.repository_owner  }}/learning-nextauth:${{ github.sha }}

      # Build and push the Docker image
      - name: Build and Push Docker Image
        if: github.event_name == 'push' || github.event_name == 'workflow_dispatch'
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/learning-nextauth:latest, ghcr.io/${{ github.repository_owner }}/learning-nextauth:${{ github.sha }}

      # Example: You could add a second tag for GitHub SHA
      # tags: username/nextjs-app:latest,username/nextjs-app:${{ github.sha }}
